theme: garth-jekyll-theme

title: This is Garth
description: "Write an awesome description for your new site here. It will appear in your document head meta (for Google search results) and in your feed.xml site description."

collections:
  posts:
    permalink: /posts/:title

logo: https://avatars3.githubusercontent.com/u/1177460?v=3&s=300
